version: '3'

services:
  app:
    build: .
    volumes:
      - ./data:/usr/src/app/data
      - ./config.json:/usr/src/app/config.json
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
